### ISSUE TITLE
Genericize EitherMatcher

### ISSUE THREAD

**Issue by nicosuave** [dry-rb/dry-matcher#11]
Since both `Either` and `Try` implement `success?`, I suggest modifying `Dry::Matcher::EitherMatcher` to call `success?` & `failure?` rather than `right?` & `left?`.

**Comment by nicosuave** [comment]
I will submit a PR if this is desired

**Comment by timriley** [comment]
@nicosuave I'd love to see this, please go ahead with the PR!

**Comment by timriley** [comment]
This has been done now.
