### ISSUE TITLE
Ruby 2.7 deprecations warnings fix

### ISSUE THREAD

**Issue by orthodoX** [dry-rb/dry-matcher#29]
Ruby 2.7 is throwing deprecations warnings for the latest release of this gem.

## Examples
`dry-matcher-0.8.3/lib/dry/matcher.rb:42: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`

## Resources
https://bloggie.io/@kinopyo/how-to-fix-ruby-2-7-warning-using-the-last-argument-as-keyword-parameters-is-deprecated

**Comment by flash-gordon** [comment]
Please provide a reproducible example. Also, keep in mind that 2.7 comes with built-in pattern matching support. Personally, I don't use dry-matcher since dry-monads support PM [out of the box](https://dry-rb.org/gems/dry-monads/1.3/pattern-matching/).
