### ISSUE TITLE
undefined method `is_a?' for #<Dry::Matcher::Evaluator:0x00007f7736b0ae78>

### ISSUE THREAD

**Issue by Josiassejod1** [dry-rb/dry-matcher#31]
## Describe the bug

We have an api response that we send through a contract. That contract expects a hash response along with other attributes. After looking through the message payload, all the expect values are their, but the built in matcher is saying that is_a? is missing

## Expected behavior

Failure or Success based on API response

## My environment

- Affects my production application: YES
- Ruby version: ...
- OS: ...

**Comment by solnic** [comment]
Could you provide a backtrace?

**Comment by Josiassejod1** [comment]
```
File /app/vendor/bundle/ruby/2.6.0/gems/dry-matcher-0.8.3/lib/dry/matcher/evaluator.rb line 49 in block in method_missing
File /app/vendor/bundle/ruby/2.6.0/gems/dry-matcher-0.8.3/lib/dry/matcher/evaluator.rb line 49 in fetch
File /app/vendor/bundle/ruby/2.6.0/gems/dry-matcher-0.8.3/lib/dry/matcher/evaluator.rb line 49 in method_missing
File /app/vendor/bundle/ruby/2.6.0/gems/dry-transaction-0.13.0/lib/dry/transaction/step_adapters/around.rb line 14 in call
File /app/vendor/bundle/ruby/2.6.0/gems/dry-transaction-0.13.0/lib/dry/transaction/step_adapters/raw.rb line 11 in call
File /app/vendor/bundle/ruby/2.6.0/gems/dry-transaction-0.13.0/lib/dry/transaction/step_adapter.rb line 41 in call
File /app/vendor/bundle/ruby/2.6.0/gems/dry-transaction-0.13.0/lib/dry/transaction/step_adapter.rb line 41 in call
File /app/vendor/bundle/ruby/2.6.0/gems/dry-transaction-0.13.0/lib/dry/transaction/step.rb line 54 in block in call
File /app/vendor/bundle/ruby/2.6.0/gems/dry-transaction-0.13.0/lib/dry/transaction/step.rb line 61 in with_broadcast
File /app/vendor/bundle/ruby/2.6.0/gems/dry-transaction-0.13.0/lib/dry/transaction/step.rb line 54 in call
File /app/vendor/bundle/ruby/2.6.0/gems/dry-transaction-0.13.0/lib/dry/transaction/stack.rb line 19 in block (3 levels) in compile
File /app/vendor/bundle/ruby/2.6.0/gems/dry-monads-1.3.5/lib/dry/monads/right_biased.rb line 57 in bind
File /app/vendor/bundle/ruby/2.6.0/gems/dry-transaction-0.13.0/lib/dry/transaction/stack.rb line 19 in block (2 levels) in compile
File /app/vendor/bundle/ruby/2.6.0/gems/dry-transaction-0.13.0/lib/dry/transaction/step.rb line 54 in call
File /app/vendor/bundle/ruby/2.6.0/gems/dry-transaction-0.13.0/lib/dry/transaction/stack.rb line 19 in block (3 levels) in compile
File /app/vendor/bundle/ruby/2.6.0/gems/dry-monads-1.3.5/lib/dry/monads/right_biased.rb line 57 in bind
File /app/vendor/bundle/ruby/2.6.0/gems/dry-transaction-0.13.0/lib/dry/transaction/stack.rb line 19 in block (2 levels) in compile
File /app/vendor/bundle/ruby/2.6.0/gems/dry-transaction-0.13.0/lib/dry/transaction/step.rb line 54 in call
File /app/vendor/bundle/ruby/2.6.0/gems/dry-transaction-0.13.0/lib/dry/transaction/stack.rb line 19 in block (3 levels) in compile
File /app/vendor/bundle/ruby/2.6.0/gems/dry-monads-1.3.5/lib/dry/monads/right_biased.rb line 57 in bind
File /app/vendor/bundle/ruby/2.6.0/gems/dry-transaction-0.13.0/lib/dry/transaction/stack.rb line 19 in block (2 levels) in compile
File /app/vendor/bundle/ruby/2.6.0/gems/dry-transaction-0.13.0/lib/dry/transaction/stack.rb line 12 in call
File /app/vendor/bundle/ruby/2.6.0/gems/dry-transaction-0.13.0/lib/dry/transaction/instance_methods.rb line 28 in call
```

**Comment by solnic** [comment]
Could you actually provide a script that reproduces this problem? It seems to be a misuse of the API that's just not handled in a nice way but I won't figure it out without a reproduction script.

**Comment by Josiassejod1** [comment]
@solnic  Found what the issue was

Basically we where making a call to a contract that was failing and instead of return a Result object, we just called return

```
MyService.call(params) do |result|
   result.success? do |result|
      return Success(result)
   end

     result.failure? do |_error|
        return result #undefined method `is_a?'
     end

end
```

**Comment by Josiassejod1** [comment]
If you had a friendlier response that would be awesome since I felt like I was beating my for hours trying to figure this out

**Comment by solnic** [comment]
@Josiassejod1 I'm not sure why you didn't find my response friendly but I'm sorry that you felt like it was - it wasn't my intention. When you report a bug and don't provide *at least* a meaningful backtrace, it's very hard for a maintainer to figure out what the problem is. A full backtrace is always a must (or at least as close to a full backtrace as possible) and a script/test that reproduces the problem is the most helpful thing to provide and it'll significantly speed up the process of addressing the problem. That's why I asked if you could provide a backtrace first, then you provided a partial backtrace and so I could only guess that it's probably a misuses of the API (which it was) that didn't result in a nice exception handling on the library side. That's why I then asked for a reproduction script, because I could run it locally and quickly figure it out.

Anyhow, I guess this could be improved by making `Evaluator` a standard `Object` descendant rather than a `BasicObject`.

**Comment by Josiassejod1** [comment]
You are right in your assumption that I rang the bell before I really dug into this, but I wanted to further investigate and get to the core of it myself. Appreciate it, and let me know how I could help further.

**Comment by solnic** [comment]
@Josiassejod1 sounds good 🙂 I just opened a PR that should make things better in cases like yours.

**Comment by Josiassejod1** [comment]
> @Josiassejod1 sounds good 🙂 I just opened a PR that should make things better in cases like yours.

Thanks for the help
